// src/lib/constants.ts
export const MASTER_TALKS = [
  { id: 1, title: "¿Conoce bien a Dios?" },
  { id: 2, title: "¿Sobreviviremos a los últimos días?" },
  { id: 3, title: "Avancemos con la organización unida de Jehová" },
  { id: 4, title: "El mundo que nos rodea prueba que Dios existe" },
  { id: 5, title: "Ayuda práctica para las familias" },
  { id: 6, title: "Qué aprendemos del diluvio universal" },
  { id: 7, title: "Imitemos al 'Padre de tiernas misericordias'" },
  { id: 8, title: "Vivamos para hacer la voluntad de Dios, no la nuestra" },
  { id: 9, title: "Escuchemos y pongamos en práctica la Palabra de Dios" },
  { id: 10, title: "Seamos honrados en todo" },
  { id: 11, title: "Imitemos a Jesús, y no seamos parte del mundo" },
  { id: 12, title: "A Dios le importa cómo vemos la autoridad" },
  { id: 13, title: "Cómo ve Dios el sexo y el matrimonio" },
  { id: 14, title: "Un pueblo limpio da gloria a Jehová" },
  { id: 15, title: "'Hagamos el bien a todos'" },
  { id: 16, title: "Fortalezcamos nuestra amistad con Dios" },
  { id: 17, title: "Demos gloria a Dios con todo lo que tenemos" },
  { id: 18, title: "Haga de Jehová su 'fortaleza'" },
  { id: 19, title: "Cómo puede usted conocer su futuro" },
  { id: 20, title: "¿Ha llegado el tiempo para que Dios gobierne el mundo?" },
  { id: 21, title: "Valoremos nuestro lugar en el Reino de Dios" },
  { id: 22, title: "¿Aprovecha usted todas las ayudas espirituales que Jehová nos da?" },
  { id: 23, title: "La vida tiene propósito" },
  { id: 24, title: "¿Ha encontrado usted 'una perla muy valiosa'?" },
  { id: 25, title: "Luchemos contra el espíritu del mundo" },
  { id: 26, title: "¿Le importamos a Dios?" },
  { id: 27, title: "Cómo iniciar bien el matrimonio" },
  { id: 28, title: "Muestre respeto y amor en su matrimonio" },
  { id: 29, title: "Las responsabilidades y las recompensas que tienen los padres" },
  { id: 30, title: "Cómo mejorar la comunicación en la familia" },
  { id: 31, title: "¿Estamos al tanto de nuestras necesidades espirituales?" },
  { id: 32, title: "Cómo enfrentarse a las inquietudes de la vida" },
  { id: 33, title: "¿Habrá algún día justicia para todos?" },
  { id: 34, title: "¿Tendrá usted la marca para sobrevivir?" },
  { id: 35, title: "¿Se puede vivir para siempre? ¿Lo logrará usted?" },
  { id: 36, title: "¿Es esta vida todo lo que podemos esperar?" },
  { id: 37, title: "¿Por qué andar en el camino de Dios?" },
  { id: 38, title: "¿Cómo puede usted sobrevivir al fin del mundo?" },
  { id: 39, title: "¿En qué sentido es Jesucristo el vencedor del mundo?" },
  { id: 40, title: "¿Qué sucederá en el futuro cercano?" },
  { id: 41, title: "'Estense quietos y vean cómo los salva Jehová'" },
  { id: 42, title: "¿Puede el amor vencer al odio?" },
  { id: 43, title: "Lo que Dios espera de nosotros siempre nos beneficia" },
  { id: 44, title: "¿Cómo le benefician a usted las enseñanzas de Jesús?" },
  { id: 45, title: "Sigamos el camino que lleva a la vida" },
  { id: 46, title: "Mantengamos nuestra confianza fuerte hasta el fin" },
  { id: 48, title: "Cómo ser leales ante las pruebas" },
  { id: 49, title: "¿Viviremos algún día en una Tierra limpia?" },
  { id: 50, title: "Cómo tomar buenas decisiones" },
  { id: 51, title: "¿Está la verdad transformando su vida?" },
  { id: 52, title: "¿Quién es su Dios?" },
  { id: 53, title: "¿Piensa usted igual que Dios?" },
  { id: 54, title: "Tenga fe en Dios y sus promesas" },
  { id: 55, title: "¿Cómo puede ganarse una buena reputación ante Dios?" },
  { id: 56, title: "¿En qué líder podemos confiar?" },
  { id: 57, title: "Aguantemos la persecución" },
  { id: 58, title: "¿Quiénes son los verdaderos discípulos de Cristo?" },
  { id: 60, title: "¿Cuál es su propósito en la vida?" },
  { id: 61, title: "¿En las promesas de quién confía usted?" },
  { id: 62, title: "¿Dónde encontrará una esperanza segura?" },
  { id: 63, title: "¿Tiene usted espíritu evangelizador?" },
  { id: 64, title: "¿Amamos los placeres en vez de a Dios?" },
  { id: 65, title: "¿Cómo podemos ser pacíficos en un mundo violento?" },
  { id: 66, title: "¿Será usted un buen trabajador en la cosecha?" },
  { id: 67, title: "Medite en la Palabra de Jehová y en su creación" },
  { id: 68, title: "'Sigan perdonándose con generosidad'" },
  { id: 69, title: "¿Por qué es importante mostrar amor desinteresado?" },
  { id: 70, title: "¿Por qué se merece Dios toda nuestra confianza?" },
  { id: 71, title: "Ahora es el momento de estar despiertos" },
  { id: 72, title: "El amor identifica a la religión verdadera" },
  { id: 73, title: "Consigamos que nuestro corazón sea sabio" },
  { id: 74, title: "Jehová está pendiente de nosotros" },
  { id: 75, title: "Demuestre que apoya el gobierno de Dios" },
  { id: 76, title: "¿Pueden los principios bíblicos ayudarnos a afrontar los problemas de nuestro tiempo?" },
  { id: 77, title: "'Sean siempre hospitalarios'" },
  { id: 78, title: "Sirva a Jehová con alegría" },
  { id: 79, title: "¿A quién prefiere como amigo?" },
  { id: 80, title: "¿Confía usted en la ciencia o en la Biblia?" },
  { id: 81, title: "¿Quiénes están preparados para hacer discípulos?" },
  { id: 83, title: "¿Tienen que obedecer los cristianos los Diez Mandamientos?" },
  { id: 84, title: "¿Escapará usted de lo que le espera a este mundo?" },
  { id: 85, title: "Buenas nuevas en un mundo violento" },
  { id: 86, title: "Cómo lograr que Dios escuche nuestras oraciones" },
  { id: 87, title: "¿Qué relación tiene usted con Dios?" },
  { id: 88, title: "Por qué vivir de acuerdo con las normas de la Biblia" },
  { id: 89, title: "¡Venga a beber el agua de la verdad!" },
  { id: 90, title: "Esfuércese por conseguir la vida que realmente es vida" },
  { id: 91, title: "La presencia y la gobernación del Mesías" },
  { id: 92, title: "El papel de la religión en los asuntos del mundo" },
  { id: 93, title: "¿Cuándo se acabarán los desastres naturales?" },
  { id: 94, title: "La religión verdadera satisface las necesidades de la sociedad humana" },
  { id: 95, title: "¡No caiga en la trampa del ocultismo!" },
  { id: 96, title: "¿Cuál es el futuro de la religión?" },
  { id: 97, title: "Permanezcamos sin culpa en medio de una generación torcida" },
  { id: 98, title: "'La escena de este mundo está cambiando'" },
  { id: 99, title: "Por qué se puede confiar en la Biblia" },
  { id: 100, title: "Haga amistades que duren para siempre" },
  { id: 101, title: "Jehová, el 'Gran Creador'" },
  { id: 102, title: "Prestémosle atención a 'la palabra profética'" },
  { id: 103, title: "Cómo ser verdaderamente felices" },
  { id: 104, title: "Padres, ¿están construyendo con materiales resistentes al fuego?" },
  { id: 105, title: "Cómo obtener consuelo en toda tribulación" },
  { id: 106, title: "Dios dará su merecido a los que arruinan la tierra" },
  { id: 107, title: "Eduquemos nuestra conciencia, y nos irá bien" },
  { id: 108, title: "Mire al futuro sin miedo" },
  { id: 109, title: "El Reino de Dios está cerca" },
  { id: 110, title: "La familia feliz es la que pone a Dios en primer lugar" },
  { id: 111, title: "La humanidad recuperará la salud por completo" },
  { id: 113, title: "Joven, ¿cómo puedes ser feliz y tener éxito?" },
  { id: 114, title: "Aprecie las maravillas de la creación de Dios" },
  { id: 115, title: "Protéjase de las astutas trampas de Satanás" },
  { id: 116, title: "Sea sabio al elegir sus compañías" },
  { id: 117, title: "Cómo vencer el mal con el bien" },
  { id: 118, title: "Veamos a los jóvenes como los ve Jehová" },
  { id: 119, title: "Por qué es provechoso que los cristianos se mantengan separados del mundo" },
  { id: 120, title: "Razones para someterse hoy al gobierno de Dios" },
  { id: 121, title: "Una hermandad mundial sobrevivirá a la mayor calamidad de la historia" },
  { id: 124, title: "Razones para confiar en el origen divino de la Biblia" },
  { id: 125, title: "Por qué necesita la humanidad un rescate" },
  { id: 126, title: "¿Quién puede ser salvo?" },
  { id: 127, title: "¿Qué nos sucede cuando morimos?" },
  { id: 128, title: "¿Es el infierno realmente un lugar de tormento?" },
  { id: 129, title: "¿Enseña la Biblia que Dios es una trinidad?" },
  { id: 130, title: "La Tierra existirá para siempre" },
  { id: 132, title: "La resurrección: una victoria sobre la muerte" },
  { id: 133, title: "¿Importa lo que creemos sobre el origen de los seres humanos?" },
  { id: 134, title: "¿Deben los cristianos observar el sábado?" },
  { id: 135, title: "La santidad de la vida y la sangre" },
  { id: 136, title: "¿Aprueba Dios las imágenes en la adoración?" },
  { id: 137, title: "¿De verdad tuvieron lugar los milagros de la Biblia?" },
  { id: 138, title: "Vivamos con buen juicio en un mundo perverso" },
  { id: 139, title: "Sabiduría piadosa en un mundo de orientación científica" },
  { id: 140, title: "¿Quién es Jesucristo en realidad?" },
  { id: 141, title: "¿Cuándo dejará de gemir la creación humana?" },
  { id: 142, title: "Por qué refugiarse en Jehová" },
  { id: 143, title: "Confiemos en el Dios de todo consuelo" },
  { id: 144, title: "Una congregación leal bajo la dirección de Cristo" },
  { id: 145, title: "¿Quién es como Jehová nuestro Dios?" },
  { id: 146, title: "Utilice la educación para alabar a Jehová" },
  { id: 147, title: "Confiemos en que Jehová tiene el poder para salvarnos" },
  { id: 148, title: "¿Ve usted la vida como la ve Dios?" },
  { id: 149, title: "¿Anda usted con Dios?" },
  { id: 150, title: "¿Está este mundo condenado a la destrucción?" },
  { id: 151, title: "Jehová es 'una altura segura' para su pueblo" },
  { id: 152, title: "¿Cuándo y por qué vendrá el verdadero Armagedón?" },
  { id: 153, title: "Estemos muy pendientes del 'impresionante día de Jehová'" },
  { id: 154, title: "El gobierno del hombre, pesado en la balanza" },
  { id: 155, title: "¿Ha llegado la hora del juicio de Babilonia?" },
  { id: 156, title: "¿Es el Día del Juicio un tiempo de temor, o de esperanza?" },
  { id: 157, title: "Cómo adornan los cristianos la enseñanza divina" },
  { id: 158, title: "Seamos valerosos y confiemos en Jehová" },
  { id: 159, title: "Cómo encontrar seguridad en un mundo peligroso" },
  { id: 160, title: "Protejamos nuestra identidad cristiana" },
  { id: 161, title: "¿Por qué sufrió y murió Jesús?" },
  { id: 162, title: "Liberados de un mundo de oscuridad" },
  { id: 163, title: "¿Por qué temer al Dios verdadero?" },
  { id: 164, title: "¿Sigue Dios ejerciendo la soberanía sobre la Tierra?" },
  { id: 165, title: "¿A qué valores concedemos más importancia?" },
  { id: 166, title: "¿Qué es la verdadera fe, y cómo se demuestra?" },
  { id: 167, title: "Actuemos con sabiduría en este mundo insensato" },
  { id: 168, title: "Cómo sentirse seguro en este mundo turbulento" },
  { id: 169, title: "¿Por qué debemos guiarnos por la Biblia?" },
  { id: 170, title: "¿Quién es el único que puede gobernar bien a la humanidad?" },
  { id: 171, title: "Usted puede disfrutar de la vida en paz ahora y para siempre" },
  { id: 172, title: "¿Qué posición tenemos ante Dios?" },
  { id: 173, title: "¿Le importa a Dios qué religión tengamos?" },
  { id: 174, title: "¿Quién será digno de entrar en el nuevo mundo de Dios?" },
  { id: 175, title: "¿Qué pruebas demuestran la autenticidad de la Biblia?" },
  { id: 176, title: "¿Cuándo tendremos verdadera paz y seguridad?" },
  { id: 177, title: "¿A quién podemos acudir en tiempos de angustia?" },
  { id: 178, title: "Andemos en el camino de la integridad" },
  { id: 179, title: "Rechace las fantasías mundanales; busque las realidades del Reino" },
  { id: 180, title: "¿Por qué debe ser real para nosotros la esperanza de la resurrección?" },
  { id: 181, title: "¿Faltará menos de lo que usted cree?" },
  { id: 182, title: "¿Qué está haciendo por nosotros el Reino de Dios?" },
  { id: 183, title: "Alejemos la mirada de lo que es inútil" },
  { id: 184, title: "¿Es la muerte el final de todo?" },
  { id: 185, title: "¿Influye la verdad en su vida?" },
  { id: 186, title: "Unidos al feliz pueblo de Dios" },
  { id: 187, title: "¿Cómo es posible que un Dios de amor permita la maldad?" },
  { id: 188, title: "¿Ha puesto usted su confianza en Jehová?" },
  { id: 189, title: "Andar con Dios nos beneficia ahora y para siempre" },
  { id: 190, title: "Una familia unida y feliz para siempre" },
  { id: 191, title: "Cómo vencen al mundo la fe y el amor" },
  { id: 192, title: "¿Anda usted por el camino que lleva a la vida eterna?" },
  { id: 193, title: "Pronto se nos librará de la angustia mundial" },
  { id: 194, title: "Cómo nos beneficia la sabiduría divina" }
];

export const SPEAKER_ROLES = [
  { value: 'Siervo Ministerial', label: 'Siervo Ministerial' },
  { value: 'Anciano', label: 'Anciano' },
];

export const APP_ID = 'speaker-planner';

export const getTalksPath = (userId: string) => `/artifacts/${APP_ID}/users/${userId}/speakers`;